name: DeployToProd

on:
  push:
    branches: [ produccion ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - name: DeployToProd script
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_PRIV_KEY }}" > ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PUB_KEY }}" > ~/.ssh/id_rsa.pub
          chmod 600 ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa.pub
          ssh -o "StrictHostKeyChecking=no" ubuntu@52.45.214.38 "cd /home/congreso/public_html/ && git pull origin produccion && pnpm install && pnpm run build && pm2 restart nextjs-congreso && exit"